### ISSUE TITLE
Gitpodify the project 

### ISSUE THREAD

**Issue by Utkarshn10** [Utkarshn10/RecipeBae#9]
- Automate project’s development setup using Gitpod
- Add Gitpod button to the README.md
- 
You can refer this [link](https://www.gitpod.io/blog/gitpodify).

**Comment by Prasad-mutnale** [comment]
I want to fix this issue can you assign me? 
## Gitpod
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/Utkarshn10/RecipeBae)

**Comment by Utkarshn10** [comment]
Hey @Prasad-mutnale thanks for contributing, please go ahead with this. Issue Assigned.

**Comment by Prasad-mutnale** [comment]
opening PR
